<?php
session_start();
include 'db.php';

$status = "error";
$title = "Upload Failed";
$message = "Unknown error occurred.";

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // 1. Sanitize Inputs
    $title_input = $conn->real_escape_string($_POST['title']);
    $description = $conn->real_escape_string($_POST['description']);
    $report_date = $conn->real_escape_string($_POST['report_date']);
    $category = $conn->real_escape_string($_POST['category']); 

    // 2. File Upload Handling
    $target_dir = "../uploads/";
    if (!is_dir($target_dir)) {
        mkdir($target_dir, 0777, true);
    }
    
    // 3. Secure File Renaming (Timestamp + Random to prevent collisions/special chars)
    $original_name = basename($_FILES["pdf_file"]["name"]);
    $file_type = strtolower(pathinfo($original_name, PATHINFO_EXTENSION));
    $clean_name = preg_replace("/[^a-zA-Z0-9]/", "", pathinfo($original_name, PATHINFO_FILENAME)); // Remove special chars
    $new_file_name = $clean_name . "_" . time() . "_" . rand(1000,9999) . "." . $file_type;
    $target_file = $target_dir . $new_file_name;

    // 4. Validate File Type
    if($file_type != "pdf") {
        $status = "error";
        $title = "Invalid File Type";
        $message = "Only PDF files are allowed.";
    } else {
        // 5. Move File
        if (move_uploaded_file($_FILES["pdf_file"]["tmp_name"], $target_file)) {
            // 6. Insert with SQL Injection Protection
            // Note: $new_file_name is safe because it's generated by us. $title_input etc are escaped above.
            $sql = "INSERT INTO adminpdfupload (title, filename, description, report_date, category) 
                    VALUES ('$title_input', '$new_file_name', '$description', '$report_date', '$category')";
            
            if ($conn->query($sql) === TRUE) {
                $status = "success";
                $title = "File Uploaded";
                $message = "<strong>" . htmlspecialchars($title_input) . "</strong> has been securely uploaded.";
            } else {
                // Remove file if DB insert fails
                unlink($target_file);
                $status = "error";
                $title = "Database Error";
                $message = "Error saving file record: " . $conn->error;
            }
        } else {
            $status = "error";
            $title = "Upload Error";
            $message = "Failed to move uploaded file. Check folder permissions.";
        }
    }
}

$_SESSION['flash_message'] = [
    'type' => $status,
    'title' => $title,
    'message' => $message
];

header("Location: ../admin_dashboard.php?section=files");
exit();
?>
